name: cart-ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/cart/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore and Build
      run: |
        cd src/cart
        dotnet restore
        dotnet build --configuration Release

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/cart
        file: ./src/cartsrc/src/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout k8s-manifests repo
      uses: actions/checkout@v4
      with:
        repository: mangesh22898/k8s-manifests
        token: ${{ secrets.MANIFEST_REPO_TOKEN }}
        path: manifests

    - name: Update image tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ github.run_id }}|" manifests/cart/deployment.yaml

    - name: Commit and push changes
      run: |
        cd manifests
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "[CI]: Update cart image tag"
        git push origin main
