name: checkout-ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/checkout/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build Checkout Service
      run: |
        cd src/checkout
        go mod tidy
        go build -o checkout-service main.go

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/checkout
        file: ./src/checkout/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/checkout-service:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout k8s-manifests repo
      uses: actions/checkout@v4
      with:
        repository: mangesh22898/k8s-manifests
        token: ${{ secrets.MANIFEST_REPO_TOKEN }}
        path: manifests

    - name: Update image tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/checkout-service:${{ github.run_id }}|" manifests/checkout/deployment.yaml

    - name: Commit and push changes
      run: |
        cd manifests
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "[CI]: Update checkout image tag"
        git push origin main
